apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      initContainers:
      - name: init-nginx-config
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          mkdir -p /etc/nginx/conf.d && \
          sed -e 's|${HOST}|localhost|g' \
              -e 's|${TARGET_SERVICE}|https://fdcdentalclinic.co.id/|g' \
              -e 's|${TARGET_HOST}|fdcdentalclinic.co.id|g' \
              /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/templates
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      - name: gateway-proxy
        image: reyshazni/gateway-proxy-amd
        ports:
        - containerPort: 8080
        env:
        - name: NGINX_SERVICE_URL
          value: "http://localhost:80"
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: nginx-conf
        emptyDir: {}